#!/bin/bash
which gpg || sudo apt-get install gnupg2 make
if [ ! -f apt-key.gpg ] ; then
	sudo apt-get -y -f install gnupg make
	mkdir -p gpg
	chmod 700 gpg
	cat - <<EOF | gpg2 --batch --gen-key --homedir gpg
%echo Generating a basic OpenPGP key
%no-ask-passphrase
Key-Type: RSA
Key-Length: 2048
Subkey-Type: RSA
Subkey-Length: 2048
Name-Real: gpg
Name-Comment: Generated by $0 gpg
Name-Email: gpg
Expire-Date: 0
# Do a commit here, so that we can later print "done" :-)
%commit
%echo Done
EOF
	gpg --homedir gpg --output apt-key.gpg --armor --export gpg
	gpg --homedir gpg --output gpg/gpg_key.gpg --armor --export-secret-key gpg
	gpg --homedir gpg --armor --export > apt-key.gpg
    	gpg --homedir `pwd`/gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A02CDA9F3D08B612
    	sudo apt-key adv --keyserver keyserver.ubuntu.com --recv A02CDA9F3D08B612
    	gpg --homedir `pwd`/gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E66C775AEBFE6C7D
    	sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E66C775AEBFE6C7D
fi
